[display]
fullscreen = true
window_size_x = 1920
window_size_y = 1080
v_sync = false

[audio]
sources = 128

[controls]
mouse_sensitivity = 0.003

[misc]
laser_sight = false
debug = true
scenario = "waves"
